// <auto-generated />
namespace WebApiHelloWorld.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class primamigrazione : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primamigrazione));
        
        string IMigrationMetadata.Id
        {
            get { return "201803210852428_prima migrazione"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
